server:
    port: 8761

eureka:
    client:
        registry-with-eureka: false
        fetch-registry: false

logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF
